repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: local
    hooks:
      - id: precommit-script
        name: custom precommit script
        entry: powershell.exe -NoProfile -ExecutionPolicy Bypass -File precommit.ps1
        language: system
        files: \.(py|md|txt|rst|yaml|yml)$
