repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        name: codespell (typo checker)
        entry: codespell
        language: system
        types: [text, python, yaml]
        files: \.(py|txt|md|rst|yaml|yml)$
        args:
          - --check-filenames
          - --quiet
